@extends('layouts.app')
@section('title', 'Antropólogo Jean Segata é indicado ao Prêmio Pesquisador Gaúcho 2022 por pesquisas sobre os impactos sociais da Covid-19')

@section('content')
    <section class="container container-text sem_"><div class="pb-3">Por <a href="estrutura">Paola Falceta</a> em 24 de agosto, 2022</div>
        
        <div class="row">
            <div class="col-lg-9 noticia">
            <h3>Antropólogo Jean Segata é indicado ao Prêmio Pesquisador Gaúcho 2022 por pesquisas sobre os impactos sociais da Covid-19</h3>
                <div class="row pt-3">
                    <img class="img-fluid" height="20" src="images\assets\img\noticias\Jean-Segata.png">
                </div> 
                <div class="row pt-3"> 
                    <p>Por Rede Covid-19 Humanidades MCTI, 24/08/2022</p>
                    <p>Jean Segata, professor do Departamento de Antropologia e do Programa de Pós-Graduação em Antropologia Social (PPGAS), é o indicado da Comissão de Pesquisa Instituto de Filosofia e Ciências Humanas da Universidade do Rio Grande do Sul (Compesq IFCH/UFRGS) para o Prêmio Pesquisador Gaúcho 2022, da Fundação de Amparo à Pesquisa do Estado do Rio Grande do Sul (FAPERGS). Em sua 12ª edição e com o tema “Ciência Gera Desenvolvimento”, a premiação reconhece o trabalho de pesquisadores e destaca a importância do investimento em ciência, inovação e tecnologia como alavanca para o desenvolvimento do Rio Grande do Sul.</p>
                    <p>Segata coordena a Rede Covid-19 Humanidades MCTI, maior projeto desde 2020 em termos de orçamento nas Ciências Sociais Brasileiras. Com esses recursos, mais de cem pesquisadoras e pesquisadores já foram beneficiados com bolsas de pesquisa de iniciação científica, mestrado, doutorado e pós-doutorado. A iniciativa tem como objetivo subsidiar, por meio de pesquisas qualitativas, ações que considerem as implicações científicas, tecnológicas, sociais, políticas, históricas e culturais da pandemia de modo múltiplo e situado. Trata-se de um projeto estruturado em duas fases: “A Covid-19 no Brasil: análise e resposta aos impactos sociais da pandemia entre profissionais de saúde e população em isolamento”, realizado entre 2020 e meados de 2022, e “A Covid-19 no Brasil 2: análise e resposta aos impactos sociais da imunização, tratamento, práticas e ambientes de cuidado e recuperação de afetados”, iniciado em julho de 2022. A Rede ainda se interliga a diversos projetos parceiros e recebe apoio de iniciativas da sociedade civil, como a Associação de Vítimas e Familiares de Vítimas da Covid-19 (AVICO Brasil).</p>
                    <p>A Rede Covid-19 Humanidades MCTI integra o conjunto de ações financiadas para o enfrentamento da pandemia via Rede Vírus MCTI e é financiada com recursos da Financiadora de Estudos e Projetos (FINEP) e do Ministério da Ciência, Tecnologia e Inovações (MCTI). É liderada pelo PPGAS/UFRGS e mobiliza pesquisadoras e pesquisadores de diferentes áreas das Ciências Humanas, Sociais e da Saúde, no Brasil e no Exterior. Em sua segunda fase, conta com a parceria da Fundação Oswaldo Cruz (Fiocruz), da Universidade Federal de Santa Catarina (UFSC), da Universidade Federal do Rio Grande do Norte (UFRN), do Centro Universitário para o Desenvolvimento do Alto Vale do Itajaí (UNIDAVI), da University College of London e da Universidade Federal do Pampa (UNIPAMPA).</p>
                    <p><strong>Acesso à produção científica da Rede Covid-19 Humanidades MCTI</strong></p>
                    <p>Em consonância com os princípios da Ciência Aberta, a Rede Covid-19 Humanidades MCTI faz uso da ferramenta Google Scholar para compilar, medir e acompanhar o impacto das pesquisas desenvolvidas por sua equipe. A Ciência Aberta é definida como atividade científica praticada de modo aberto, colaborativo e transparente, em todos os domínios do conhecimento, desde as ciências fundamentais até às ciências sociais e humanidades. Sua ênfase recai sobre os aspectos sociais da ciência, sobretudo sobre sua publicidade, reprodutividade, transparência e sustentabilidade.</p>
                    <p>A Rede Covid-19 Humanidades MCTI disponibiliza os metadados e número de citações das produções científicas geradas tanto pelas e pelos pesquisadores associados quanto por aquelas e aqueles vinculados a projetos de pesquisa parceiros no perfil <a href="https://scholar.google.com/citations?view_op=list_works&hl=en&hl=en&user=1LGElMoAAAAJ&pagesize=80&sortby=title">https://scholar.google.com/citations?view_op=list_works&hl=en&hl=en&user=1LGElMoAAAAJ&pagesize=80&sortby=title</a>. Assim, as contribuições ficam visíveis e passíveis de busca e acesso a qualquer pessoa interessada. Em sua primeira fase, a Rede Covid-19 Humanidades MCTI reuniu 140 publicações, das quais derivam 611 citações (dados de 25 de julho de 2022). No ano de 2020, registrou 88 citações; em 2021, 305; e, até meados de 2022, 206. Os dois artigos com mais alcance obtiveram 74 e 69 citações respectivamente, o que é uma marca expressiva. O acompanhamento das citações aponta que os frutos do trabalho da Rede vêm contribuindo de forma crescente para outras pesquisas, o que atesta a relevância da iniciativa e a importância da construção do conhecimento em Humanidades para fins práticos.</p>
                    <p>Mais informações sobre a Rede Covid-19 Humanidades MCTI estão disponíveis no site <a href="https://www.ufrgs.br/redecovid19humanidades/index.php/br">https://www.ufrgs.br/redecovid19humanidades/index.php/br</a></p>
                    <p>Saiba mais sobre o Prêmio Pesquisador Gaúcho em <a href="https://fapergs.rs.gov.br/premio-pesquisador-gaucho-2022-regulamento">https://fapergs.rs.gov.br/premio-pesquisador-gaucho-2022-regulamento</a></p>
                    
                </div>         
            </div>
        
            <div class="col-lg-3 leiamais">
                <div class="row border-start"><h5>Leia mais</h5></div>
                <div class="row border-start mt-3 ps-2"><a href="/juri-simbolico-do-tribunal-permanente-dos-povos-condena-bolsonaro-por-crimes-contra-a-humanidade-durante-a-pandemia">JÃºri simbÃ³lico do Tribunal Permanente dos Povos condena Bolsonaro por crimes contra a humanidade durante a pandemia</a></div>
                <div class="row border-start mt-3 ps-2"><a href="/antropologo-jean-segata-e-indicado-ao-premio-pesquisador-gaucho-2022-por-pesquisas-sobre-os-impactos-sociais-da-covid-19">AntropÃ³logo Jean Segata Ã© indicado ao PrÃªmio Pesquisador GaÃºcho 2022 por pesquisas sobre os impactos sociais da Covid-19</a></div>
                <div class="row border-start mt-3 ps-2"><a href="/associacao-reune-parentes-e-pessoas-que-tiveram-a-doenca-queixa-crime-afirma-que-presidente-cometeu-nove-crimes-na-conducao-do-enfrentamento-a-pandemia-e-cita-inercia-da-pgr">Barroso envia Ã  PGR acusaÃ§Ã£o contra Bolsonaro sobre pandemia e queixa-crime lista 9 crimes</a></div>
                <div class="row border-start mt-3 ps-2"><a href="/covid-longa-e-tema-do-decimo-informe-da-rede-trabalhadores-covid-19-do-cesteh-fiocruz">Covid longa Ã© tema do dÃ©cimo informe da Rede Trabalhadores & Covid-19 do Cesteh-Fiocruz</a></div>
                <div class="row border-start mt-3 ps-2"><a href="/mesmo-com-o-fim-da-situacao-de-emergencia-sanitaria-parte-da-populacao-ainda-sofre-com-sequelas-da-covid-19">Mesmo com o fim da situaÃ§Ã£o de emergÃªncia sanitÃ¡ria, parte da populaÃ§Ã£o ainda sofre com sequelas da covid-19</a></div>
           </div>
        </div>   
    </section>
@endsection