@extends('layouts.app')
@section('title', 'Mesmo com o fim da situação de emergência sanitária, parte da população ainda sofre com sequelas da covid-19')

@section('content')
    <section class="container container-text sem_"><div class="pb-3">Por <a href="estrutura">Paola Falceta</a> em 2 de junho de 2022</div>
        
        <div class="row">
            <div class="col-lg-9 noticia">
            <h3>Mesmo com o fim da situação de emergência sanitária, parte da população ainda sofre com sequelas da covid-19</h3>
                <div class="row pt-3">
                    <img class="img-fluid" src="images\assets\img\noticias\Flavio-Dutra-9882-2.jpg">
                </div> 
                <div class="row pt-3"> 
                    <p>Letícia Pasuch, Jornal da UFRGS – 02 de junho de 2022</p>
                    <p><strong>Saúde | Necessidade de políticas públicas eficientes de atendimento às pessoas com a chamada “covid longa” é ressaltada por profissionais de saúde, defensores de direitos humanos e pesquisadores</strong></p>
                    <p>Passados pouco mais de dois anos do início da pandemia de coronavírus, o ministro da Saúde Marcelo Queiroga assinou, 
                        no dia 22 de abril, a portaria que declara o <a href="https://www.gov.br/saude/pt-br/assuntos/noticias/2022/abril/ministerio-da-saude-declara-fim-da-emergencia-em-saude-publica-de-importancia-nacional-pela-covid-19">
                        fim da Emergência em Saúde Pública de Importância Nacional (ESPIN)</a> no Brasil. 
                        Mas, para muitas pessoas, os impactos da pandemia permanecerão por muito tempo. Apesar de haver cerca de 30 milhões de casos recuperados no país, 
                        notificados pelo <a href="https://covid.saude.gov.br/">Painel Coronavírus</a> , ainda há em torno de 240 mil casos em acompanhamento – muitos deles relacionados a consequências ocasionadas pelo vírus. 
                        Segundo a Organização Mundial da Saúde, de <a href="https://agenciabrasil.ebc.com.br/internacional/noticia/2022-03/oms-covid-19-prolongada-atinge-10-20-dos-infectados">10% a 20% da população que teve covid-19 desenvolve sequelas</a>  após a recuperação da fase aguda da doença.</p>
                    <p>É o caso de Cláudia Cruz, 51 anos, de Porto Alegre, que teve covid grave em fevereiro de 2021 e convive ainda hoje com complicações. Ela precisou ser internada, ficou entubada por 21 dias e, após, passou por um longo período de reabilitação. “Na época, eu não tinha voz, e hoje ela não é mais a mesma. Se falo demais, fico rouca, com pigarros, e tenho problemas na garganta”, detalha. No início, mal conseguia levantar os braços e pernas e ficar em pé porque sentia muita dor e desconforto. Paciente considerada obesa, Cláudia perdeu 30 quilos após a covid. Também teve queda de cabelo severa, custou a recuperar o olfato e o paladar, e ainda hoje apresenta hipersensibilidade nas pernas e nos pés. “Às vezes eu também perco o equilíbrio, tenho muita tontura ao deitar e levantar; barulho em excesso incomoda”, conta.</p>       
                    <p>Apesar de muitas sequelas não serem totalmente conhecidas, já se sabe que o sistema respiratório não é o único órgão afetado a longo prazo pela contaminação do vírus. Os sintomas considerados <a href="https://www.ufrgs.br/telessauders/documentos/telecondutas/Telecondutas_pos_covid.pdf">mais comuns das condições pós-covid-19</a>  são fadiga, cefaleia, déficit de atenção, perda de cabelo, perda de olfato e paladar e dor nas articulações. <a href="http://dasu.unb.br/images/Material_educativo/Guia_de_sade_mental_ps-pandemia_no_brasil.pdf?_ga=2.192006378.1503439980.1648997972-804038250.1648997947">Pesquisas recentes</a> apontam que a covid-19 tem sido cada vez mais reconhecida como uma doença sistêmica, com desdobramentos secundários e consequências cognitivas e comportamentais – como o aumento de transtornos psicológicos, sejam provocados por ação do vírus no sistema nervoso, sejam por experiências traumáticas. Essas condições reforçam a necessidade de haver serviços especializados para atender os grupos acometidos. </p>
                    <p><strong>Tratamentos pós-covid disponibilizados em Porto Alegre</strong></p>
                    <p>Segundo informações do site institucional da Secretaria Estadual de Saúde, em 2021 foram destinados 7 milhões de reais para investimentos na estruturação de 10 ambulatórios pós-covid no Rio Grande do Sul. A capital, de acordo com informações da assessoria da Secretaria Municipal de Saúde de Porto Alegre, conta com um <a href="https://prefeitura.poa.br/sms/noticias/ambulatorio-pos-covid-faz-mais-de-600-atendimentos-em-diferentes-especialidades">ambulatório de reabilitação pós-covid</a> , que funciona dentro do Centro de Saúde IAPI. Atualmente, cerca de 50 pessoas ainda seguem em acompanhamento no serviço, a maior parte delas desde o ano passado. A pasta também destaca uma <a href="https://prefeitura.poa.br/sms/noticias/saude-registra-reducao-de-pacientes-na-reabilitacao-pos-covid#:~:text=O%20ambulat%C3%B3rio%20de%20reabilita%C3%A7%C3%A3o%20p%C3%B3s,dois%20primeiros%20meses%20do%20ano.">redução no encaminhamento</a>  de pessoas para o atendimento nos dois primeiros meses deste ano. </p>
                    <p>De acordo com Aline Casaril, fisioterapeuta e coordenadora do ambulatório, a demanda surgiu em julho de 2021 porque muitas pessoas com sequelas de covid procuravam o serviço de fisioterapia no Centro de Saúde IAPI. Passaram, então, a também serem oferecidos serviços de psicologia, enfermagem, nutrição, fonoaudiologia, acupuntura e osteopatia, e cerca de 200 pessoas já receberam atendimento desde a implementação.</p>
                    <p>Aline observa que as principais complicações do vírus tiveram uma mudança de curso conforme o aumento da vacinação. “Quando iniciamos em julho (de 2021), eram pessoas que estavam com sequelas daquele boom de março, que ainda com sintomas buscavam atendimento. Foi o auge. Naquela época, as queixas eram bem mais fortes”, conta. Para os pacientes que se infectaram pós-vacina, Aline visualiza outro quadro. “É bem mais leve, a maioria não ficou internada, nenhum que veio este ano ficou entubado, e observamos menos alterações metabólicas.” Segundo a profissional, a faixa etária de pacientes atendidos não alterou, mantendo-se na média de 50 anos, apesar de muitos jovens também terem procurado o serviço.</p>
                    <p>Quando os casos são mais graves, os pacientes podem ser encaminhados ao serviço de fisiatria e reabilitação do Hospital de Clínicas de Porto Alegre (HCPA), que já atendia internamente a pós-covid, mas foi reorganizado desde julho de 2021 para também receber pacientes que chegam das redes básicas de saúde. De acordo com a médica e chefe do serviço, Simone Zanette, são atendidos pacientes com sequela motora, fadiga, perda de força, miopatia de ambiente crítico – ocasionados pela longa permanência em UTI – e com questões neurológicas. A equipe profissional é composta, além da fisiatria, por terapia ocupacional, enfermagem, educação física, fonoaudiologia, assistência social, nutrição e psicologia – este juntamente com o serviço de psicologia da UFRGS.</p>
                    <p>“É um serviço de reabilitação com vários profissionais atuando no sentido de fazer com que a pessoa melhore a capacidade, apesar das lesões definitivas, favorecendo a qualidade de vida e o bem-estar”Simone Zanette</p>
                    <p>Aline percebe o Sistema Único de Saúde (SUS) como uma referência durante esse período. “Se observou que com a pandemia quem foi o pioneiro nesses ambulatórios foi o SUS, em função das demandas que surgiram e das questões sociais que se agravaram. Muitas pessoas que antes não usavam [o SUS] porque tinham plano de saúde se surpreenderam em poder ter um bom atendimento, e que às vezes poderia ser o único caminho para o pós-covid.” Aline, porém, notou que demorou um pouco, no começo, para que fosse divulgado esse fluxo do ambulatório – tanto internamente, nas unidades de saúde, quanto para a população procurar os serviços.</p>
                    <p>A fisioterapeuta também encontrou algumas dificuldades na gestão, como troca de equipes justamente nas épocas com maior número de casos da doença e unidades de saúde apenas com consultas regulares, sem poder fazer encaminhamento para o pós-covid. Desde o começo do ambulatório, Aline conta que também tentou solicitar mais material, como bicicletas, mesas e cadeiras para mobiliar o espaço e qualificar o serviço, mas ainda não conseguiu comprar por causa das burocracias envolvidas. “Já passou um ano e ainda não estou com os equipamentos que poderiam ter vindo antes”, lamenta.</p>
                    <p><strong>Reparação, assistência e luta por políticas públicas</strong></p>
                    <p>Em meio a tantas pessoas afetadas pelos diversos impactos da pandemia, voluntários buscam amparar esses grupos e fomentar políticas protetivas e de enfrentamento à doença. É o caso da Associação de Vítimas e Familiares de Vítimas da Covid-19 (Avico). A partir da indignação por ter perdido sua mãe por conta do vírus, em março de 2021, a assistente social e presidente da Avico, Paola Falceta, convidou seu amigo, Gustavo Bernardes – que tinha sido hospitalizado, quase faleceu e ficou com sequelas da covid – para dar início à associação. “Entendi que era importantíssimo todo o conhecimento que eu e meu colega, que é advogado e defensor de direitos, tínhamos; seria necessário para colocar essa pauta como pública e para discussão na sociedade”, diz Paola.</p>
                    <p>Em suma, o objetivo principal da Avico é a defesa dos direitos humanos dos familiares das vítimas e dos sobreviventes da covid-19, perpassando por diversas políticas públicas de saúde, assistência social, previdência, trabalho e educação. A Associação também tem uma rede de parceria com outros movimentos sociais e com universidades como a UFRGS, nos cursos de Antropologia e Jornalismo, e busca ampliar a rede de parceiros e entidades que, nas palavras de Paola, estão inconformadas com a postura do Estado brasileiro de negação da emergência pública e da crise sanitária.</p>
                    <p>“O que a gente não imaginava é que a Avico teria que se tornar um movimento social nacional. Criamos para ser regional e para trabalhar aqui no RS, mas somos a única associação exclusiva de familiares de vítimas e sobreviventes da covid do país” Paola Falceta</p>
                    <p>Com três eixos de atuação – jurídico, apoio psicossocial e mobilização e controle social –, a ideia é ajudar desde pessoas que precisam de apoio jurídico ou de assessoria para lidar com burocracias trabalhistas e de previdência até usuários que tentam dar continuidade ao tratamento pós-covid e não conseguem acompanhamento adequado. “A gente informa as pessoas onde podem buscar esses serviços e, se violados esses direitos, como podem fazer para acionar isso juridicamente”, explica Paola. Foi também organizado um grupo de enlutados, composto por familiares das vítimas que estavam em sofrimento psíquico e mental.</p>
                    <p>Cláudia foi uma das pessoas que passou por dificuldades durante sua recuperação pós-covid. Ao sair do hospital, precisou fazer revisão e acompanhamento também para sua diabetes e hipertensão, mas não teve acesso aos exames e aparelhos necessários nem foi encaminhada para tratamento pós-covid. Há pouco tempo, ela descobriu que deveria ter tido atendimento domiciliar por uma equipe especializada para monitorar seus curativos de lesões desenvolvidas por causa da covid e acredita que o motivo da ausência seja a escassez de materiais de curativos.</p>
                    <p>Ela acredita que, sem o apoio de família e amigos, não teria conseguido enfrentar todas as dificuldades durante esse período de recuperação. “A rede pública não me amparou, só a rede de solidariedade”, afirma. Em janeiro deste ano, Cláudia finalmente ganhou os devidos insumos e aparelhos para monitorar o nível de glicose no sangue. E, no início de maio, mais de um ano após sua alta, teve a primeira consulta com fisioterapia no Ambulatório do IAPI – que fica, porém, 40 quilômetros distante de sua casa. “Eu tinha que ir uma vez por semana, mas não tenho condições (financeiras).”</p>
                    <p>“É com o Auxílio-Brasil que a gente está sobrevivendo. Participando de movimentos de luta social, vejo que o investimento em saúde pós-covid e a política de assistência são irrisórios” Cláudia Cruz</p>
                    <p>No Rio Grande do Sul, o Conselho Estadual de Saúde (CES) criou um Comitê em Defesa das Vítimas de Covid para pensar formas de atender os grupos impactados pela pandemia, o que, segundo Paola – participante da iniciativa –, foi uma maneira de mobilizar instituições e colocar o assunto em pauta. Recentemente, o comitê foi recebido na Assembleia Legislativa do estado, que lançou uma Frente Parlamentar em defesa das vítimas de covid. Para a assistente social, é uma ação inédita. “Até então, não éramos nem atendidos. Fizemos audiência pública, uma série de documentos e resoluções sobre covid, o Conselho Nacional [de Saúde] ficou muito interessado.”</p>
                    <p>O presidente do CES/RS, Claudio Augustin, foi acometido pela covid-19 em dezembro de 2020. Foi entubado e ficou internado até agosto de 2021, e hoje ainda precisa se alimentar por sonda de gastrostomia, tem dificuldades motoras e fica a maior parte do tempo acamado. Segundo a vice-presidente do Conselho, Inara Ruas, a situação dele foi o que mais motivou a criação do comitê. “Pro Estado, ou as pessoas faleceram, ou estão recuperadas. Nas estatísticas brasileiras, o Cláudio está 100% recuperado”, aponta Inara, justificando a necessidade de atenção do poder público às pessoas que convivem com sequelas.</p>
                    <p>Inara relembra que as sequelas do vírus são as mais diversas possíveis e que grande parte da população não tem plano de saúde para conseguir facilmente um tratamento. “Nisso, é preciso que o Estado – governos federal, estadual e municipal – invista em políticas públicas, tenha espaços para reabilitação dos pacientes, treine as equipes, pois as sequelas também passam pelos familiares e pelos enlutados”, afirma. Segundo Inara, por lei, o Estado deveria investir anualmente 12% da receita líquida de impostos em saúde. Ela lembra que, todos os anos, o Conselho Estadual de Saúde reprova o relatório anual de gestão porque essa porcentagem não foi atingida. “Em 2020, foi (investido) apenas 7% em saúde pública no SUS. O CES está atento e comprovando o que não é investido”, sinaliza.</p>
                    <p>Pesquisadora, Paola também percebe que não existe um protocolo nacional criado pelo Ministério da Saúde que oriente como devem ser feitos os atendimentos e tratamentos para o pós-covid. “O que os municípios e estados vêm fazendo é uma atuação ineficiente e incompetente em relação à saúde da população, que tem sequelas da covid longa.” Ela lembra que não há monitoramento da secretaria municipal sobre os casos recuperados e que as capacitações necessárias estão sendo dadas apenas com dois anos de pandemia.</p>
                    <p><strong>A pandemia é maior do que a contaminação pelo vírus</strong></p>
                    <p>Os efeitos de saúde e também socioeconômicos gerados pela pandemia são fatores que <a href="https://www.gov.br/mcti/pt-br/acompanhe-o-mcti/noticias/2022/04/mcti-pesquisa-vai-estudar-os-efeitos-sociais-de-longo-prazo-da-covid-19-em-profissionais-da-saude-e-em-pacientes-com-sequelas">serão estudados nos próximos meses</a>  por uma rede de pesquisadores no Rio Grande do Sul. A Rede Covid-19 Humanidades MCTI (Ministério da Ciência, Tecnologia e Inovações), sediada no Programa de Pós-graduação em Antropologia Social da UFRGS, irá se debruçar nos efeitos em larga escala e duração da pandemia, buscando produzir subsídios às ações de enfrentamento à doença. </p>
                    <p>Jean Segata, coordenador da rede e professor no departamento de Antropologia da Universidade, afirma que, de um ponto de vista antropológico, a pandemia é muito mais do que um vírus: é um conjunto de situações que envolvem desde desigualdade socioeconômica até degradação ambiental – problemas sociais de toda ordem se colocam em evidência nesses momentos. Segata também afirma que o fim da circulação do vírus não significa o fim da pandemia, antropologicamente, pois há uma materialidade que ainda resiste nos corpos das pessoas, que são as sequelas. Segundo ele, apesar de o SUS ter um papel fundamental desde a sua constituição, sobretudo nesse período, não há políticas públicas plenamente desenhadas para atendimento.</p>
                    <p>Para Jean, as experiências vividas em uma pandemia são muito distintas devido às questões de classe social. O pesquisador defende que, com as populações sendo atingidas em diferentes intensidades, os seus direitos também precisam ser tratados em multiplicidade.</p>
                    <p>“A gente sabe que, no Brasil, pobre não tem direito de adoecer porque tem de trabalhar. A experiência da dor crônica com a covid é diferente entre pobres e ricos: a classe média alta vai procurar serviço médico e consegue atendimento, seja pelo meio privado ou por planos de saúde, como um direito. Só que esse direito é para todos” Jean Segata</p>
                    <p>O decreto do fim de uma emergência sanitária envolve negociações colocadas dentro de uma estatística considerada tolerável. Mas o docente se questiona: “Tolerável para quem? Para o Estado? Para as autoridades de saúde? Porque obviamente não é tolerável para quem está sofrendo”.</p>
                    <p>Com experiência anterior em pesquisa relacionada às epidemias provocadas pelo mosquito Aedes aegypti, como a zika, a dengue, a chikungunya e a febre amarela, desde 2014 Jean vinha pesquisando o processo de erradicação de epidemias. Com o decreto do fim da de zika, em 2016, a doença foi se tornando “normalizada”, mas segue fazendo parte do cotidiano de uma parcela da população que desenvolveu sequelas. Através de relatos, estudou que os sintomas mais evidentes acontecem nos primeiros momentos da infecção e que logo cessam, mas havia indivíduos que, seis anos depois, ainda carregavam essas dores. Para ele, são pessoas consideradas invisibilizadas, que muitas vezes precisam provar judicialmente que ainda sentem dores para, assim, receber direitos. </p>
                    <p>Agora, com os demais pesquisadores da rede, Jean buscará acompanhar a pandemia quando está tecnicamente terminada e dar visibilidade a esses processos invisibilizados. Com <a href="http://www.ufrgs.br/ufrgs/noticias/rede-covid-19-humanidades-mcti-tem-nova-fase-de-pesquisa-apoiada-com-recursos-da-finep">convênio assinado</a> no dia 26 de abril, o projeto “A Covid-19 no Brasil 2: análise e resposta aos impactos sociais da imunização, tratamento, práticas e ambientes de cuidado e recuperação de afetados” inicia em maio e terá duração de 24 meses.</p>
                    <p>Para acessar a matéria original clique <a href="https://www.ufrgs.br/jornal/mesmo-com-o-fim-da-situacao-emergencial-de-saude-populacao-ainda-sofre-com-sequelas-da-covid-19/">aqui.</a></p>
                </div>         
            </div>
            
            <div class="col-lg-3 leiamais">
                <div class="row border-start"><h5>Leia mais</h5></div>
                <div class="row border-start mt-3 ps-2"><a href="/audiencia-debate-a-situacao-das-sequelas-das-vitimas-da-covid-no-rio-grande-do-sul">Audiência debate a situação das sequelas das vítimas da covid no Rio Grande do Sul</a></div>
                <div class="row border-start mt-3 ps-2"><a href="/estamos-ha-quase-tres-anos-com-a-covid-19-no-brasil-e-ainda-nada-foi-feito-critica-presidenta-da-avico-no-pleno-do-cns-sobre-familiares-e-vitimas-da-doenca">“Estamos há quase três anos com a Covid-19 no Brasil e ainda nada foi feito”, critica presidenta da Avico, no Pleno do CNS, sobre familiares e vítimas da doença</a></div>
                <div class="row border-start mt-3 ps-2"><a href="/audiencias-publicas-debaterao-a-situacao-das-sequelas-das-vitimas-da-covid-no-estado">COLOCAR TITULO</a></div>
           </div>
        </div>   
    </section>
@endsection